### ISSUE TITLE
Credentials Commited

### ISSUE THREAD

**Issue by jakes44** [unc-cs-sg/cc-inventory#2]
Please remove the credentials (credentials.txt) before someone abuses this. 

https://github.com/unc-cs-sg/cc-inventory/blob/943aee03f92659d92c2d806ae92cf8bdf6836f19/credentials.txt#L1

@yicheng-w 
https://scontent-atl3-1.xx.fbcdn.net/v/t1.15752-9/50737504_827907194208331_6801005400964464640_n.png?_nc_cat=108&_nc_ht=scontent-atl3-1.xx&oh=143a4120204c60c14c623a338c6c8cde&oe=5CFEBC5F

**Comment by yicheng-w** [comment]
Also, please consider changing password to non-English.
